name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Ejecuta una vez al día a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: sechafer
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          force: true
          directory: dist
          github_token: ${{ABJZWMCNWTKVIGHKKZCZNY3GJZWGI}}
