-
name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # Genera la serpiente cada día a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v2

      - name: Instala Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instala las dependencias
        run: |
          pip install -r requirements.txt

      - name: Genera la serpiente
        run: |
          python3 ./generate_snake.py

      - name: Subir los archivos generados
        uses: actions/upload-artifact@v2
        with:
          name: Snake Animation
          path: output/snake.svg
